[build]
  publish = "dist"
  functions = "interactividad.js"

[functions]
  directory = "interactividad.js"
  node_bundler = "esbuild"
  external_node_modules = ["some-external-module"]
  included_files = ["files/*.md"]

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[functions]
  directory = "https://github.com/dominiodesconocido/franproyekt.git"
